# Generated by Django 3.2.3 on 2021-05-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_html',
            field=models.FileField(upload_to='../media/blog/post_html/'),
        ),
    ]
