# Generated by Django 3.2.3 on 2021-05-13 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_blog_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_html',
            field=models.FileField(upload_to='./blog/post_html/'),
        ),
    ]
