# Generated by Django 3.2.3 on 2021-05-16 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_blog_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edited_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
