# Generated by Django 3.2.3 on 2021-05-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='blog/images/default_thumbnail.png', upload_to='blog/images/'),
        ),
    ]
