# Generated by Django 3.2.3 on 2021-05-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_html',
            field=models.FileField(upload_to='../blog/templates/blog_posts/'),
        ),
    ]
