# Generated by Django 3.2.3 on 2021-05-28 02:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_blog_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_html',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='', location='/code/blog/templates/'), upload_to='blog_posts'),
        ),
    ]
