# Generated by Django 3.2.3 on 2021-06-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_blog_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog_html',
        ),
        migrations.AddField(
            model_name='post',
            name='blog_content',
            field=models.TextField(null=True),
        ),
    ]
