# Generated by Django 3.2.3 on 2021-06-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210603_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_content',
            new_name='content',
        ),
    ]
