# Generated by Django 3.2.3 on 2021-05-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_details',
        ),
        migrations.AddField(
            model_name='project',
            name='preview',
            field=models.ImageField(default='../demo_media/portfolio/images/default_preview.png', upload_to='../demo_media/portfolio/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
    ]
